version: '3'
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: imgroot
      MYSQL_DATABASE: wp
      MYSQL_USER: userwp
      MYSQL_PASSWORD: sukses123
    volumes:
    - ./mysql:/var/lib/mysql

  web:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./code:/code
    - ./site.conf:/etc/nginx/conf.d/site.conf

  php:
    #Build menggunakan dockerfile
    build: ./
    volumes:
    - ./code:/code
