version: '3' #versi docker-compose yang digunakan
services:
  #definisikan service yang mau dijalankan, untuk wp ada 3 (db,webserver,php)
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: imgroot
      MYSQL_DATABASE: wp
      MYSQL_USER: userwp
      MYSQL_PASSWORD: sukses123
    volumes: #aku mau persistent storage folder mysql di lokal mounting /var/lib/mysql di container
    - ./mysqlku:/var/lib/mysql

  web:
    image: nginx:latest
    ports: #ekspose port biar bisa diakses dari internet port 80
    - "80:80"
    volumes:
    - ./code:/code #persistent volume untuk menempatkan file website
    - ./site.conf:/etc/nginx/conf.d/site.conf #bikin konfigurasi nginx, root foldernya dikasi /code

  php:
    build: ./ #Build php menggunakan Dockerfile
    volumes: #phpnya mau bisa dieksekusi dimana ? difolder tempat websitenya dong yaitu /code
    - ./code:/code
